modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/pau101/Boat-Collision-Fix/issues"
[[mods]]
    modId="boatcollisionfix"
    version="${version}"
    displayName="Boat Collision Fix"
    displayURL="https://minecraft.curseforge.com/projects/boat-collision-fix"
    authors="pau101"
    description="Fixes MC-156980 and MC-136367"
[[dependencies.boatcollisionfix]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.boatcollisionfix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
